### ISSUE TITLE
I wonder why but after I pulled, server status remains as 'checking' and login button doesn't invoke anything.

### ISSUE THREAD

**Issue by chlee0925** [KenLSM/SOCPrint#10]
I wonder why but after I pulled, server status remains as 'checking' and login button doesn't invoke anything. @KenLSM

**Comment by KenLSM** [comment]
Probably the JS causing some errors. Will check on it

**Comment by KenLSM** [comment]
Can you try pulling the previous version, just before the beautify on serverscript.js

**Comment by chlee0925** [comment]
Oh okay. No problem! :)

**Comment by KenLSM** [comment]
Should be fixed. Pull again. Can close this issue if it is fixed on your side too.

**Comment by chlee0925** [comment]
Yup. Works beautifully now. Case closed! :) :+1:
